In [3]:
import csv

with open("學生成績1.csv", mode='r',encoding="utf-8",newline="") as file:
    csvReader = csv.reader(file)
    #next(csvReader)
    #for row in csvReader:
    #    print(row)
    students = list(csvReader)
students

[['姓名', '國文', '英文', '數學', '地理', '歷史'],
 ['溫重意', '91', '74', '81', '54', '84'],
 ['王梅劭', '62', '76', '89', '75', '64'],
 ['蘇婷婷', '63', '87', '86', '55', '50'],
 ['王雅慧', '81', '62', '73', '99', '78'],
 ['陳樂紫', '70', '59', '58', '59', '76'],
 ['鄭琇亞', '58', '99', '87', '81', '69'],
 ['李湘婷', '67', '65', '94', '92', '82'],
 ['陳得映', '67', '84', '79', '70', '63'],
 ['游倫城', '83', '80', '60', '81', '87'],
 ['孫火清', '54', '66', '94', '58', '100']]

In [13]:
import pandas as pd
dataFrame1 = pd.DataFrame(students)
dataFrame1.columns = dataFrame1.iloc[0]
dataFrame2 = dataFrame1.iloc[1:]
dataFrame2

0    姓名  國文  英文  數學  地理   歷史
1   溫重意  91  74  81  54   84
2   王梅劭  62  76  89  75   64
3   蘇婷婷  63  87  86  55   50
4   王雅慧  81  62  73  99   78
5   陳樂紫  70  59  58  59   76
6   鄭琇亞  58  99  87  81   69
7   李湘婷  67  65  94  92   82
8   陳得映  67  84  79  70   63
9   游倫城  83  80  60  81   87
10  孫火清  54  66  94  58  100